### ISSUE TITLE
Clarify relation to official(?) repo in Readme

### ISSUE THREAD

**Issue by mk-pmb** [LoneWolfHT/headanim#2]
Hi! What's the relation between this repo and https://github.com/minetest-mods/playeranim ? In #1 it sounds like the other is newer, so is this one deprecated? Would be nice if you could explain that in the Readme.

**Comment by LoneWolfHT** [comment]
playeranim used to use old and hacky methods to achieve player head rotation. It was rewritten to take advantage of a new MT feature (The same one this uses). That github repo contains the new version of that mod.

My version is just quick and simple head animations, and so can't do all the fancy stuff playeranim does.

I've added a link to it in the readme with a comment.

**Comment by mk-pmb** [comment]
Thanks! Now visitors can see the pros/cons at a glance.
