### ISSUE TITLE
Very Laggy

### ISSUE THREAD

**Issue by Kyanoxia** [LoneWolfHT/headanim#3]
There is lots of visual lag when using this mod.  It looks very choppy, and not appealing.

**Comment by LoneWolfHT** [comment]
Is this in singleplayer or on a server? What other mods are in use?

**Comment by Kyanoxia** [comment]
Single and multiplayer, Linux and Windows, no other mods.  It seems to run at about 2fps, while the rest of the world is 60fps.

**Comment by LoneWolfHT** [comment]
> Single and multiplayer, Linux and Windows, no other mods.  It seems to run at about 2fps, while the rest of the world is 60fps.

It should be running at about 10FPS, which is what I'm limited to by Minetest

**Comment by Kyanoxia** [comment]
After doing a boatload of research, I found that you can, indeed get 10fps when you set dedicated server step size to 0.001.  It's kind of a weird workaround though.
